(function () {
  'use strict';

  // Auto-scraped Live IPO GMP Data (2026-09-11 08:39)
  window.GMP_DATA = [
    {
        "id": "axiom-gas-engineering",
        "name": "Axiom Gas Engineering",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "2,000",
        "closeDate": "18-Sep",
        "listingDate": "23-Sep",
        "lotSize": "\u20b949.81 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "nse",
        "name": "NSE",
        "type": "Mainboard",
        "priceBand": "\u20b9191 (10.70%)\n191 \u2193 / 310 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "8",
        "closeDate": "17-Sep",
        "listingDate": "22-Sep",
        "lotSize": "\u20b922561.57 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "kheria-autocomp",
        "name": "Kheria Autocomp",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "17-Sep",
        "listingDate": "22-Sep",
        "lotSize": "\u20b946.44 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "sonaselection-india",
        "name": "Sonaselection India",
        "type": "Mainboard",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "150",
        "closeDate": "17-Sep",
        "listingDate": "22-Sep",
        "lotSize": "\u20b9141.57 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "jindal-supreme",
        "name": "Jindal Supreme",
        "type": "Mainboard",
        "priceBand": "\u20b919 (20.43%)\n11 \u2193 / 19 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "161",
        "closeDate": "16-Sep",
        "listingDate": "21-Sep",
        "lotSize": "\u20b9124.88 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "ss-retail",
        "name": "SS Retail",
        "type": "Mainboard",
        "priceBand": "\u20b930 (7.08%)\n30 \u2193 / 30 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "35",
        "closeDate": "16-Sep",
        "listingDate": "21-Sep",
        "lotSize": "\u20b9500.00 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "hero-motors",
        "name": "Hero Motors",
        "type": "Mainboard",
        "priceBand": "\u20b98 (9.52%)\n8 \u2193 / 8 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "178",
        "closeDate": "16-Sep",
        "listingDate": "21-Sep",
        "lotSize": "\u20b91000.00 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "vama-wovenfab",
        "name": "Vama Wovenfab",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "400",
        "closeDate": "15-Sep",
        "listingDate": "18-Sep",
        "lotSize": "\u20b949.54 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "shakti-polytarp",
        "name": "Shakti Polytarp",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "2,000",
        "closeDate": "15-Sep",
        "listingDate": "18-Sep",
        "lotSize": "\u20b926.93 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "quanto-agroworld",
        "name": "Quanto Agroworld",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "2,000",
        "closeDate": "15-Sep",
        "listingDate": "18-Sep",
        "lotSize": "\u20b931.02 Cr",
        "status": "Upcoming",
        "indicator": "U",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "injecto-polymers",
        "name": "Injecto Polymers",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "11-Sep\nGMP: 0",
        "listingDate": "17-Sep",
        "lotSize": "\u20b956.12 Cr",
        "status": "Upcoming",
        "indicator": "O",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "century-business-media",
        "name": "Century Business Media",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,600",
        "closeDate": "11-Sep\nGMP: 0",
        "listingDate": "17-Sep",
        "lotSize": "\u20b917.11 Cr",
        "status": "Upcoming",
        "indicator": "O",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "manika-plastech",
        "name": "Manika Plastech",
        "type": "Mainboard",
        "priceBand": "\u20b913 (30.23%)\n13 \u2193 / 20 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "348",
        "closeDate": "11-Sep\nGMP: 13",
        "listingDate": "17-Sep",
        "lotSize": "\u20b9125.50 Cr",
        "status": "Upcoming",
        "indicator": "O",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "maharaja-speedex-india",
        "name": "Maharaja & Speedex India",
        "type": "SME",
        "priceBand": "\u20b930 (16.13%)\n15 \u2193 / 30 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "600",
        "closeDate": "10-Sep\nGMP: 30",
        "listingDate": "16-Sep",
        "lotSize": "\u20b980.13 Cr",
        "status": "Upcoming",
        "indicator": "O",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "om-galaxy",
        "name": "Om Galaxy",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,600",
        "closeDate": "10-Sep\nGMP: 0",
        "listingDate": "16-Sep",
        "lotSize": "\u20b9105.00 Cr",
        "status": "Upcoming",
        "indicator": "O",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "name",
        "name": "NAME",
        "type": "Mainboard",
        "priceBand": "GMP",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "LOT",
        "closeDate": "OPEN",
        "listingDate": "BOA DT",
        "lotSize": "IPO SIZE",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "veegaland-developers",
        "name": "Veegaland Developers",
        "type": "Mainboard",
        "priceBand": "\u20b925 (17.86%)\n18 \u2193 / 33 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "107",
        "closeDate": "10-Sep\nGMP: 25",
        "listingDate": "16-Sep",
        "lotSize": "\u20b9210.00 Cr",
        "status": "Upcoming",
        "indicator": "O",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "panchatv-bharat",
        "name": "Panchatv Bharat",
        "type": "SME",
        "priceBand": "\u20b97 (5.00%)\n7 \u2193 / 7 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,000",
        "closeDate": "10-Sep\nGMP: 7",
        "listingDate": "16-Sep",
        "lotSize": "\u20b924.58 Cr",
        "status": "Upcoming",
        "indicator": "O",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "raksan-transformers",
        "name": "Raksan Transformers",
        "type": "SME",
        "priceBand": "\u20b928 (10.26%)\n25 \u2193 / 28 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "400",
        "closeDate": "10-Sep\nGMP: 28",
        "listingDate": "16-Sep",
        "lotSize": "\u20b9150.50 Cr",
        "status": "Upcoming",
        "indicator": "O",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "lcc-projects",
        "name": "LCC Projects",
        "type": "Mainboard",
        "priceBand": "\u20b951 (34.93%)\n17 \u2193 / 51 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 3,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "102",
        "closeDate": "9-Sep\nGMP: 40",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9427.14 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "karamtara-engineering",
        "name": "Karamtara Engineering",
        "type": "Mainboard",
        "priceBand": "\u20b969 (27.17%)\n40 \u2193 / 75 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 3,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "59",
        "closeDate": "9-Sep\nGMP: 75",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9875.00 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "amtech-esters",
        "name": "Amtech Esters",
        "type": "SME",
        "priceBand": "\u20b911 (14.67%)\n5 \u2193 / 11 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 2,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,600",
        "closeDate": "9-Sep\nGMP: 11",
        "listingDate": "15-Sep",
        "lotSize": "\u20b917.88 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "asset-reconstruction",
        "name": "Asset Reconstruction",
        "type": "Mainboard",
        "priceBand": "\u20b914 (10.07%)\n14 \u2193 / 30 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "107",
        "closeDate": "9-Sep\nGMP: 24",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9732.97 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "manipal-payment-and-identity-solutions",
        "name": "Manipal Payment and Identity Solutions",
        "type": "Mainboard",
        "priceBand": "\u20b94 (1.18%)\n4 \u2193 / 38 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "44",
        "closeDate": "9-Sep\nGMP: 8",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9805.00 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "vinod-texworld",
        "name": "Vinod Texworld",
        "type": "SME",
        "priceBand": "\u20b915 (15.96%)\n4 \u2193 / 20 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "9-Sep\nGMP: 20",
        "listingDate": "15-Sep",
        "lotSize": "\u20b942.83 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "steamhouse",
        "name": "Steamhouse",
        "type": "Mainboard",
        "priceBand": "\u20b923 (28.40%)\n18 \u2193 / 23 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 2,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "185",
        "closeDate": "9-Sep\nGMP: 20",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9414.00 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "infrax-renewable",
        "name": "Infrax Renewable",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "9-Sep\nGMP: 0",
        "listingDate": "15-Sep",
        "lotSize": "\u20b940.88 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "rentomojo",
        "name": "Rentomojo",
        "type": "Mainboard",
        "priceBand": "\u20b9135 (33.42%)\n79 \u2193 / 155 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 4,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "37",
        "closeDate": "9-Sep\nGMP: 143",
        "listingDate": "15-Sep",
        "lotSize": "\u20b91255.57 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "kanohar-electricals",
        "name": "Kanohar Electricals",
        "type": "Mainboard",
        "priceBand": "\u20b9240 (37.97%)\n190 \u2193 / 240 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 90,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "23",
        "closeDate": "8-Sep\nGMP: 218",
        "listingDate": "11-Sep",
        "lotSize": "\u20b91055.74 Cr",
        "status": "Upcoming",
        "indicator": "C",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "glass-wall-systems",
        "name": "Glass Wall Systems",
        "type": "Mainboard",
        "priceBand": "\u20b945 (24.73%)\n20 \u2193 / 66 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 81,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "82",
        "closeDate": "8-Sep\nGMP: 56",
        "listingDate": "11-Sep",
        "lotSize": "\u20b9427.89 Cr",
        "status": "Upcoming",
        "indicator": "C",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "prasol-chemicals",
        "name": "Prasol Chemicals",
        "type": "Mainboard",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 165 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 3,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "22",
        "closeDate": "8-Sep\nGMP: 30",
        "listingDate": "11-Sep",
        "lotSize": "\u20b9500.00 Cr",
        "status": "Upcoming",
        "indicator": "C",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "name",
        "name": "NAME",
        "type": "Mainboard",
        "priceBand": "GMP",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "LOT",
        "closeDate": "OPEN",
        "listingDate": "BOA DT",
        "lotSize": "IPO SIZE",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "pranav-constructions",
        "name": "Pranav Constructions",
        "type": "Mainboard",
        "priceBand": "\u20b951 (41.13%)\n23 \u2193 / 52 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 126,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "120",
        "closeDate": "7-Sep\nGMP: 42.5",
        "listingDate": "10-Sep",
        "lotSize": "\u20b9351.03 Cr",
        "status": "Upcoming",
        "indicator": "C",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "apana-logistics",
        "name": "Apana Logistics",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 10 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 1,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "2,000",
        "closeDate": "7-Sep\nGMP: 10",
        "listingDate": "10-Sep",
        "lotSize": "\u20b934.14 Cr",
        "status": "Upcoming",
        "indicator": "C",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "qualiance-international",
        "name": "Qualiance International",
        "type": "SME",
        "priceBand": "\u20b981 (63.78%)\n50 \u2193 / 81 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 459,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,000",
        "closeDate": "4-Sep\nGMP: 55",
        "listingDate": "9-Sep",
        "lotSize": "\u20b945.11 Cr",
        "status": "Upcoming",
        "indicator": "",
        "subjectToSauda": 0,
        "kostak": 0
    }
];
})();
