(function () {
  'use strict';

  // Sample Live IPO GMP Data
  window.GMP_DATA = [
    {
      id: "bajaj-housing",
      name: "Bajaj Housing Finance",
      type: "Mainboard",
      priceBand: "₹66 - ₹70",
      price: 70, // upper band
      gmp: 58,
      gmpTrend: "up", // up, down, flat
      estListing: 128,
      gainPct: 82.86,
      subTotal: "63.60x",
      subRetail: "7.04x",
      openDate: "09 Sep",
      closeDate: "11 Sep",
      listingDate: "16 Sep",
      lotSize: 214,
      status: "Upcoming", // Open, Upcoming, Closed, Listed
      subjectToSauda: 10000,
      kostak: 500
    },
    {
      id: "pn-gadgil",
      name: "PN Gadgil Jewellers",
      type: "Mainboard",
      priceBand: "₹456 - ₹480",
      price: 480,
      gmp: 230,
      gmpTrend: "up",
      estListing: 710,
      gainPct: 47.92,
      subTotal: "--",
      subRetail: "--",
      openDate: "10 Sep",
      closeDate: "12 Sep",
      listingDate: "17 Sep",
      lotSize: 31,
      status: "Upcoming",
      subjectToSauda: 6500,
      kostak: 0
    },
    {
      id: "tolins-tyres",
      name: "Tolins Tyres",
      type: "Mainboard",
      priceBand: "₹215 - ₹226",
      price: 226,
      gmp: 30,
      gmpTrend: "down",
      estListing: 256,
      gainPct: 13.27,
      subTotal: "23.89x",
      subRetail: "21.55x",
      openDate: "09 Sep",
      closeDate: "11 Sep",
      listingDate: "16 Sep",
      lotSize: 66,
      status: "Upcoming",
      subjectToSauda: 1800,
      kostak: 0
    },
    {
      id: "gala-precision",
      name: "Gala Precision Engineering",
      type: "Mainboard",
      priceBand: "₹503 - ₹529",
      price: 529,
      gmp: 255,
      gmpTrend: "up",
      estListing: 784,
      gainPct: 48.20,
      subTotal: "201.41x",
      subRetail: "91.95x",
      openDate: "02 Sep",
      closeDate: "04 Sep",
      listingDate: "09 Sep",
      lotSize: 28,
      status: "Closed",
      subjectToSauda: 5000,
      kostak: 0
    },
    {
      id: "shree-tirupati",
      name: "Shree Tirupati Balajee",
      type: "Mainboard",
      priceBand: "₹78 - ₹83",
      price: 83,
      gmp: 38,
      gmpTrend: "up",
      estListing: 121,
      gainPct: 45.78,
      subTotal: "124.74x",
      subRetail: "73.22x",
      openDate: "05 Sep",
      closeDate: "09 Sep",
      listingDate: "12 Sep",
      lotSize: 180,
      status: "Open",
      subjectToSauda: 4500,
      kostak: 300
    },
    {
      id: "my-mudra",
      name: "My Mudra Fincorp",
      type: "SME",
      priceBand: "₹104 - ₹110",
      price: 110,
      gmp: 50,
      gmpTrend: "flat",
      estListing: 160,
      gainPct: 45.45,
      subTotal: "108.31x",
      subRetail: "156.40x",
      openDate: "05 Sep",
      closeDate: "09 Sep",
      listingDate: "12 Sep",
      lotSize: 1200,
      status: "Open",
      subjectToSauda: 40000,
      kostak: 0
    },
    {
      id: "namasta-exports",
      name: "Namasta Exports",
      type: "SME",
      priceBand: "₹75 - ₹79",
      price: 79,
      gmp: -5,
      gmpTrend: "down",
      estListing: 74,
      gainPct: -6.32,
      subTotal: "0.80x",
      subRetail: "1.20x",
      openDate: "11 Sep",
      closeDate: "13 Sep",
      listingDate: "18 Sep",
      lotSize: 1600,
      status: "Upcoming",
      subjectToSauda: 0,
      kostak: 0
    },
    {
      id: "boss-packaging",
      name: "Boss Packaging",
      type: "SME",
      priceBand: "₹66",
      price: 66,
      gmp: 12,
      gmpTrend: "up",
      estListing: 78,
      gainPct: 18.18,
      subTotal: "135.83x",
      subRetail: "167.33x",
      openDate: "30 Aug",
      closeDate: "03 Sep",
      listingDate: "06 Sep",
      lotSize: 2000,
      status: "Closed",
      subjectToSauda: 15000,
      kostak: 0
    },
    {
      id: "mach-conferences",
      name: "Mach Conferences",
      type: "SME",
      priceBand: "₹214 - ₹225",
      price: 225,
      gmp: 155,
      gmpTrend: "up",
      estListing: 380,
      gainPct: 68.88,
      subTotal: "196.70x",
      subRetail: "136.49x",
      openDate: "04 Sep",
      closeDate: "06 Sep",
      listingDate: "11 Sep",
      lotSize: 600,
      status: "Closed",
      subjectToSauda: 70000,
      kostak: 0
    }
  ];
})();
