(function () {
  'use strict';

  // Auto-scraped Live IPO GMP Data (2026-09-07 00:43)
  window.GMP_DATA = [
    {
        "id": "nseu",
        "name": "NSEU",
        "type": "Mainboard",
        "priceBand": "\u20b9273 (-%)\n273 \u2193 / 310 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "",
        "closeDate": "",
        "listingDate": "",
        "lotSize": "-",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "manika-plastechu",
        "name": "Manika PlastechU",
        "type": "Mainboard",
        "priceBand": "\u20b9-- (-%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "",
        "closeDate": "11-Sep",
        "listingDate": "17-Sep",
        "lotSize": "",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "veegaland-developersu",
        "name": "Veegaland DevelopersU",
        "type": "Mainboard",
        "priceBand": "\u20b930 (21.43%)\n18 \u2193 / 30 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "107",
        "closeDate": "10-Sep",
        "listingDate": "16-Sep",
        "lotSize": "\u20b9210.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "steamhouseu",
        "name": "SteamhouseU",
        "type": "Mainboard",
        "priceBand": "\u20b9-- (-%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "",
        "closeDate": "9-Sep",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9414.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "manipal-payment-and-identity-solutionsu",
        "name": "Manipal Payment and Identity SolutionsU",
        "type": "Mainboard",
        "priceBand": "\u20b930 (8.85%)\n29 \u2193 / 30 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "44",
        "closeDate": "9-Sep",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9805.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "infrax-renewable-bse-smeu",
        "name": "Infrax Renewable BSE SMEU",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "9-Sep",
        "listingDate": "15-Sep",
        "lotSize": "\u20b940.88 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "vinod-texworld-nse-smeu",
        "name": "Vinod Texworld NSE SMEU",
        "type": "SME",
        "priceBand": "\u20b94 (4.26%)\n4 \u2193 / 4 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "9-Sep",
        "listingDate": "15-Sep",
        "lotSize": "\u20b942.83 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "asset-reconstructionu",
        "name": "Asset ReconstructionU",
        "type": "Mainboard",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "107",
        "closeDate": "9-Sep",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9732.97 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "amtech-esters-bse-smeu",
        "name": "Amtech Esters BSE SMEU",
        "type": "SME",
        "priceBand": "\u20b95 (6.67%)\n5 \u2193 / 5 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,600",
        "closeDate": "9-Sep",
        "listingDate": "15-Sep",
        "lotSize": "\u20b917.88 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "rentomojou",
        "name": "RentomojoU",
        "type": "Mainboard",
        "priceBand": "\u20b9149 (36.88%)\n79 \u2193 / 155 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "37",
        "closeDate": "9-Sep",
        "listingDate": "15-Sep",
        "lotSize": "\u20b91255.57 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "lcc-projectsu",
        "name": "LCC ProjectsU",
        "type": "Mainboard",
        "priceBand": "\u20b925 (17.12%)\n17 \u2193 / 25 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "102",
        "closeDate": "9-Sep",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9427.14 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "karamtara-engineeringu",
        "name": "Karamtara EngineeringU",
        "type": "Mainboard",
        "priceBand": "\u20b955 (21.65%)\n40 \u2193 / 55 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "59",
        "closeDate": "9-Sep",
        "listingDate": "15-Sep",
        "lotSize": "\u20b9875.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "prasol-chemicalsu",
        "name": "Prasol ChemicalsU",
        "type": "Mainboard",
        "priceBand": "\u20b9115 (17.01%)\n14 \u2193 / 165 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "22",
        "closeDate": "8-Sep",
        "listingDate": "11-Sep",
        "lotSize": "\u20b9500.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "kanohar-electricalsu",
        "name": "Kanohar ElectricalsU",
        "type": "Mainboard",
        "priceBand": "\u20b9205 (32.44%)\n190 \u2193 / 205 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "23",
        "closeDate": "8-Sep",
        "listingDate": "11-Sep",
        "lotSize": "\u20b91055.74 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "glass-wall-systemsu",
        "name": "Glass Wall SystemsU",
        "type": "Mainboard",
        "priceBand": "\u20b935 (19.23%)\n20 \u2193 / 65 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "82",
        "closeDate": "8-Sep",
        "listingDate": "11-Sep",
        "lotSize": "\u20b9427.89 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "name",
        "name": "NAME",
        "type": "Mainboard",
        "priceBand": "GMP",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "LOT",
        "closeDate": "OPEN",
        "listingDate": "BOA DT",
        "lotSize": "IPO SIZE",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "pranav-constructionsu",
        "name": "Pranav ConstructionsU",
        "type": "Mainboard",
        "priceBand": "\u20b944 (35.48%)\n23 \u2193 / 44 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "120",
        "closeDate": "7-Sep",
        "listingDate": "10-Sep",
        "lotSize": "\u20b9351.03 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "apana-logistics-bse-smeu",
        "name": "Apana Logistics BSE SMEU",
        "type": "SME",
        "priceBand": "\u20b93 (5.00%)\n3 \u2193 / 3 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "2,000",
        "closeDate": "7-Sep",
        "listingDate": "10-Sep",
        "lotSize": "\u20b934.14 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "qualiance-international-nse-smeo",
        "name": "Qualiance International NSE SMEO",
        "type": "SME",
        "priceBand": "\u20b955 (43.31%)\n50 \u2193 / 55 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 13,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,000",
        "closeDate": "4-Sep\nGMP: 55",
        "listingDate": "9-Sep",
        "lotSize": "\u20b945.11 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "farm-peace-bse-smecallotted",
        "name": "Farm Peace BSE SMECALLOTTED",
        "type": "SME",
        "priceBand": "\u20b950 (84.75%)\n12 \u2193 / 50 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 1,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "2,000",
        "closeDate": "1-Sep\nGMP: 0",
        "listingDate": "4-Sep",
        "lotSize": "\u20b932.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "deepa-jewellerscallotted",
        "name": "Deepa JewellersCALLOTTED",
        "type": "Mainboard",
        "priceBand": "\u20b921.5 (12.15%)\n18 \u2193 / 55 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 43,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "84",
        "closeDate": "1-Sep\nGMP: 44",
        "listingDate": "4-Sep",
        "lotSize": "\u20b9459.72 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "rays-of-beliefcallotted",
        "name": "Rays of BeliefCALLOTTED",
        "type": "Mainboard",
        "priceBand": "\u20b920 (8.37%)\n10 \u2193 / 48 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 107,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "62",
        "closeDate": "1-Sep\nGMP: 38",
        "listingDate": "4-Sep",
        "lotSize": "\u20b9125.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "fly-hi-maritime-bse-smec",
        "name": "Fly-Hi Maritime BSE SMEC",
        "type": "SME",
        "priceBand": "\u20b91 (0.98%)\n1 \u2193 / 20 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 2,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "1-Sep\nGMP: 12.5",
        "listingDate": "4-Sep",
        "lotSize": "\u20b952.63 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "shanti-inorganics-nse-smecallotted",
        "name": "Shanti Inorganics NSE SMECALLOTTED",
        "type": "SME",
        "priceBand": "\u20b954 (65.06%)\n13 \u2193 / 54 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 142,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,600",
        "closeDate": "31-Aug\nGMP: 31",
        "listingDate": "3-Sep",
        "lotSize": "\u20b947.24 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "purple-style-labscallotted",
        "name": "Purple Style LabsCALLOTTED",
        "type": "Mainboard",
        "priceBand": "\u20b9-10 (-1.74%)\n-10 \u2193 / 34 \u2191",
        "price": 10,
        "gmp": 0,
        "estListing": 1,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "26",
        "closeDate": "31-Aug\nGMP: 7",
        "listingDate": "3-Sep",
        "lotSize": "\u20b9680.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "phychem-technologies-bse-smecallotted",
        "name": "Phychem Technologies BSE SMECALLOTTED",
        "type": "SME",
        "priceBand": "\u20b91 (1.85%)\n1 \u2193 / 3 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 20,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "2,000",
        "closeDate": "31-Aug\nGMP: 1",
        "listingDate": "3-Sep",
        "lotSize": "\u20b914.58 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "ashutosh-fibre-nse-smecallotted",
        "name": "Ashutosh Fibre NSE SMECALLOTTED",
        "type": "SME",
        "priceBand": "\u20b956 (60.87%)\n10 \u2193 / 56 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 144,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "31-Aug\nGMP: 45",
        "listingDate": "3-Sep",
        "lotSize": "\u20b956.35 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "fascinate-textiles-nse-smecallotted",
        "name": "Fascinate Textiles NSE SMECALLOTTED",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 1,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "800",
        "closeDate": "11-Aug\nGMP: 0",
        "listingDate": "20-Aug",
        "lotSize": "\u20b964.83 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "complete-sports-and-management-bse-smel-139-00-2-96-",
        "name": "Complete Sports and Management BSE SMEL@139.00 (2.96%)",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 3,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,000",
        "closeDate": "28-Aug\nGMP: 0",
        "listingDate": "2-Sep",
        "lotSize": "\u20b974.93 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "paluck-technologies-bse-smel-46-80-2-5-",
        "name": "Paluck Technologies BSE SMEL@46.80 (-2.5%)",
        "type": "SME",
        "priceBand": "\u20b99 (18.75%)\n9 \u2193 / 30 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 271,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "3,000",
        "closeDate": "28-Aug\nGMP: 25",
        "listingDate": "2-Sep",
        "lotSize": "\u20b933.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "priority-jewelsl-230-00-15-",
        "name": "Priority JewelsL@230.00 (15%)",
        "type": "Mainboard",
        "priceBand": "\u20b928 (14.00%)\n20 \u2193 / 45 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 100,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "75",
        "closeDate": "28-Aug\nGMP: 45",
        "listingDate": "2-Sep",
        "lotSize": "\u20b991.50 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "name",
        "name": "NAME",
        "type": "Mainboard",
        "priceBand": "GMP",
        "price": 0,
        "gmp": 0,
        "estListing": 0,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "LOT",
        "closeDate": "OPEN",
        "listingDate": "BOA DT",
        "lotSize": "IPO SIZE",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "esds-software-solutionl-757-00-76-46-",
        "name": "ESDS Software SolutionL@757.00 (76.46%)",
        "type": "Mainboard",
        "priceBand": "\u20b9311 (72.49%)\n247 \u2193 / 372 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 142,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "34",
        "closeDate": "28-Aug\nGMP: 360",
        "listingDate": "2-Sep",
        "lotSize": "\u20b9720.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "kwick-forensic-solutions-bse-smel-150-00-66-67-",
        "name": "Kwick Forensic Solutions BSE SMEL@150.00 (66.67%)",
        "type": "SME",
        "priceBand": "\u20b978 (86.67%)\n15 \u2193 / 85 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 289,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,600",
        "closeDate": "27-Aug\nGMP: 64",
        "listingDate": "1-Sep",
        "lotSize": "\u20b950.77 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "lumino-industriesl-110-00-34-15-",
        "name": "Lumino IndustriesL@110.00 (34.15%)",
        "type": "Mainboard",
        "priceBand": "\u20b938 (46.34%)\n38 \u2193 / 63 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 124,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "182",
        "closeDate": "27-Aug\nGMP: 56",
        "listingDate": "1-Sep",
        "lotSize": "\u20b9700.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "sumax-engineering-nse-smel-111-00-9-9-",
        "name": "Sumax Engineering NSE SMEL@111.00 (9.9%)",
        "type": "SME",
        "priceBand": "\u20b922 (21.78%)\n20 \u2193 / 36 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 162,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "25-Aug\nGMP: 35",
        "listingDate": "31-Aug",
        "lotSize": "\u20b953.40 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "annu-projectsl-72-00-27-27-",
        "name": "Annu ProjectsL@72.00 (-27.27%)",
        "type": "Mainboard",
        "priceBand": "\u20b9-7 (-7.07%)\n-7 \u2193 / 7 \u2191",
        "price": 7,
        "gmp": 0,
        "estListing": 2,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "151",
        "closeDate": "25-Aug\nGMP: 0",
        "listingDate": "31-Aug",
        "lotSize": "\u20b9175.06 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "abh-healthcare-nse-smel-99-00-2-94-",
        "name": "ABH Healthcare NSE SMEL@99.00 (-2.94%)",
        "type": "SME",
        "priceBand": "\u20b9-- (0.00%)\n0 \u2193 / 0 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 1,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "24-Aug\nGMP: 0",
        "listingDate": "28-Aug",
        "lotSize": "\u20b934.98 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "madhur-knit-nse-smel-100-00-0-",
        "name": "Madhur Knit NSE SMEL@100.00 (0%)",
        "type": "SME",
        "priceBand": "\u20b92 (2.00%)\n2 \u2193 / 16 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 1,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "1,200",
        "closeDate": "24-Aug\nGMP: 16",
        "listingDate": "28-Aug",
        "lotSize": "\u20b953.27 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "skyways-airl-124-00-10-14-",
        "name": "Skyways AirL@124.00 (-10.14%)",
        "type": "Mainboard",
        "priceBand": "\u20b933 (23.91%)\n19 \u2193 / 50 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 71,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "100",
        "closeDate": "24-Aug\nGMP: 32",
        "listingDate": "28-Aug",
        "lotSize": "\u20b9582.80 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "symbiotec-pharmalabl-988-00-0-",
        "name": "Symbiotec PharmalabL@988.00 (0%)",
        "type": "Mainboard",
        "priceBand": "\u20b9185 (18.72%)\n185 \u2193 / 410 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 75,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "15",
        "closeDate": "24-Aug\nGMP: 335",
        "listingDate": "28-Aug",
        "lotSize": "\u20b91757.00 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    },
    {
        "id": "hy-tech-engineersl-75-00-41-51-",
        "name": "Hy-Tech EngineersL@75.00 (41.51%)",
        "type": "Mainboard",
        "priceBand": "\u20b939 (73.58%)\n5 \u2193 / 45 \u2191",
        "price": 0,
        "gmp": 0,
        "estListing": 247,
        "gainPct": 0,
        "subTotal": "--",
        "subRetail": "--",
        "openDate": "283",
        "closeDate": "24-Aug\nGMP: 30",
        "listingDate": "28-Aug",
        "lotSize": "\u20b9135.73 Cr",
        "status": "Upcoming",
        "subjectToSauda": 0,
        "kostak": 0
    }
];
})();
